spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:templates/
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
